### PR TITLE
Dev like post

### PR DESCRIPTION
**Pull request by ajweaver13**

### CODE REVIEW

**Review by jamescam — APPROVED** [review]
Approved.

**Review by dawmckin — APPROVED** [review]

**Comment by mxledesma** [comment]
approve

**Review by mxledesma — APPROVED** [review]

**Review by CJPete22 — CHANGES_REQUESTED** [review]
Please Refactor to not have a seperate like and likeid class

**Comment by ajweaver13** [comment]
Ready to be reviewed again! Refactored Likes to be a join column.

**Review by CJPete22 — CHANGES_REQUESTED** [review]
Could you remove the superfluous use of "public" from the postservice interface?
Additionally there looks to be a conflict with the constructors on Profile. Can you accept the constructor that doesn't take in an id or would that break your implementation?

**Review by CJPete22 — APPROVED** [review]

**Pull request merged**
